app = "voxdocs"

[build]
image = "registry.fly.io/voxdocs:latest"

[[services]]
internal_port = 5000
protocol = "tcp"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[mounts]
source="devenv_state"
destination="/.devenv/state"
